// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "FetchURL.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::CS6210;

class FetchURLHandler : virtual public FetchURLIf {
 public:
  FetchURLHandler() {
    // Your initialization goes here
  }

  void ping() {
    // Your implementation goes here
    printf("ping\n");
  }

  void fetch(std::string& _return, const std::string& URL) {
    // Your implementation goes here
    printf("fetch\n");
  }

  int32_t getMapSize() {
    // Your implementation goes here
    printf("getMapSize\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<FetchURLHandler> handler(new FetchURLHandler());
  shared_ptr<TProcessor> processor(new FetchURLProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

