/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Project3_constants.h"

namespace CS6210 {

const Project3Constants g_Project3_constants;

Project3Constants::Project3Constants() {
}

} // namespace

