/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Project3_CONSTANTS_H
#define Project3_CONSTANTS_H

#include "Project3_types.h"

namespace CS6210 {

class Project3Constants {
 public:
  Project3Constants();

};

extern const Project3Constants g_Project3_constants;

} // namespace

#endif
